### ISSUE TITLE
json file is missing

### ISSUE THREAD

**Issue by ensk** [inuitcss/base.lists#1]
when installed with bower the json file is missing, causing an error when I try to move components with grunt-bower

**Comment by anselmh** [comment]
Hey @ensk. Sorry to be very late here. Can you tell me more about which file is missing (is it `bower.json`?) and why does `grunt-bower` need this? We don’t do anything special in the repository or exclude it in a `.bowerrc` so I wonder why this happens.

**Comment by florianbouvot** [comment]
@ensk I close this issue. Feel free to reopen it with more detail.
